### ISSUE TITLE
Does not scan all memory segments, only currently viewed one is searched

### ISSUE THREAD

**Issue by uberhalit** [rikodot/binja_native_sigscan#10]
Currently the scanner searches the viewed memory segment only, all other ones are ignored. 

https://github.com/rikodot/binja_native_sigscan/blob/2b8c6c9527470143681708165916c3a22891d691/sigscan.cpp#L405
`view->GetStart()` and `view-GetEnd()` do return the full address range, however `view->Read()` will not read past a memory segment boundry.
https://github.com/rikodot/binja_native_sigscan/blob/2b8c6c9527470143681708165916c3a22891d691/sigscan.cpp#L417
This can be verified easily by trying to read the entire memory at once and logging the return value from `view->Read()`. It will stop reading as soon as there is a non-continous memory section between two segments.

binja_coolsigmaker is correctly handling all memory segments individually: 
https://github.com/unknowntrojan/binja_coolsigmaker/blob/2ea7594879ad534c0012893444a45417f196b5cd/src/lib.rs#L316

**Comment by rikodot** [comment]
Based on my testing current version scans across all memory segments. I created a signature for a bunch of bytes in .rdata, went to .text, initiated a search for those bytes and it found them successfully. Is this what you are referring to?

**Comment by uberhalit** [comment]
Apologies for the delay, it seems like this was caused by some anti-RE segment shifting inside the analysed file, the pattern lies outside of what BN detects as a valid segment. I switched to malcat for this file.
