### ISSUE TITLE
Update for new version?

### ISSUE THREAD

**Issue by taylor310** [rikodot/binja_native_sigscan#14]
Thank you so much for your plugin. Is there any chance of an update for the most recent version of binary ninja from July?

**Comment by rikodot** [comment]
Hello, I am glad you like the plugin.
I have uploaded files for the most recent versions of binary ninja (dev + v4.1.5747) to the [release section](https://github.com/rikodot/binja_native_sigscan/releases/latest). You can download it and put it into the binary ninja plugins folder manually. I am not sure when I am going to release an update for the loader plugin.
If you have any questions or experience any issues, feel free to reopen the issue. Have a nice day.
