### ISSUE TITLE
organize menus

### ISSUE THREAD

**Issue by psifertex** [rikodot/binja_native_sigscan#2]
The plugin currently puts multiple menus inside the plugin interface when I think it might look cleaner to organize them in [submenus](https://github.com/Vector35/snippets/blob/master/__init__.py#L767-L775).

**Comment by rikodot** [comment]
Great suggestion, implemented in [this commit](https://github.com/rikodot/binja_native_sigscan/commit/7755eafa7f51a08d4459c8c7bcec728f0574fa96).
