### ISSUE TITLE
support for dev?

### ISSUE THREAD

**Issue by psifertex** [rikodot/binja_native_sigscan#3]
Right now the plugin only supports the latest stable which I think is absolutely fair and makes sense. Again, we should probably officially produce build action scripts people can use that will build cross-platform for both dev and stable to fix this.

**Comment by rikodot** [comment]
Understandable, I have customized the loader and added native binaries to support all currently available Binary Ninja versions since 3.1.3469 including dev builds. For more information follow [related loader issue](https://github.com/rikodot/binja_native_sigscan_loader/issues/1).

**Comment by psifertex** [comment]
Awesome! Thanks for the quick fix. If you don't mind, I plan to highlight this plugin and the loader for it in our next plugin highlight, it's something we'd love to encourage other authors of native plugins to consider to help discoverability / maintenance until we have a better built-in mechanism.

**Comment by rikodot** [comment]
Thanks for all the feedback, I appreciate your interest in native plugin development, I feel like there is a lot of potential hiding in here. This project started simply as my personal need to utilize a functionality with high level of performance and I only decided to release it after hearing a discussion regarding the exact same issue I was facing on one of your YouTube livestreams. The idea of highlighting my work sounds great, I am looking forward to seeing more light being brought to this area and hopefully more plugins pop-up.
